---
title: "Financing Projects"
author: "mbh038"
date: "Thursday, June 04, 2015"
header-includes:
   - \usepackage{mathtools}
   - \usepackage{amsmath}
   - \input eplain
   - \leftdisplays
output: html_document
---

## Three financial measures ofa project

In this session we learn how to evaluate the viability of a project through the use of three measures:

* Pay back time
* Net Present Value (NPV)
* Internal Rate of Return (IRR)

We will set up a spreadsheet to calculate these three, then try to work out what they are actually telling us!

A key concept we will use in all of these is that of _discounting_. This is the idea that transactions in the future are worth less, the further into the future that they occur. This is relevant to any energy generation project, which typically has large capital expenses at the beginning and then a steady drip,drip of returns every year throughout the project lifetime, which may be for 20 or more years or even many more if it is a large scale hydroelectric, tidal range or nuclear project, where final disposal and clean-up operations may not take place until several decades or even a a century or so after initial construction! The discounting idea says that those earnings or disposal costs are worth less than if they had occurrred all at once, at the beginning of the project. Eh? Let us explore this, first by measuring a the financial merits of a project without the idea of discounting

## 'Simple' Financial Measures

'Simple' measures of the financial merit of a project do not take discounting into account.

Suppose the capital cost of a wind turbine project is £100,000, and suppose that the project has net annual earnings of £10,000 over a project lifetime of 20 years. The simple payback time is the capital expense divided by the annual earnings. For this project it would be 10 years:


$$
\begin{align*}
\mathrm{Simple\ Payback\ Time}&=\dfrac{\mathrm{Capital\ Expenses}}{\mathrm{Annual\ Net\ Revenues}}\\
&=\dfrac{£100,000}{£10,000}\\
&=10\ \mathrm{years}\\
\shortintertext{\mathrm{The\ Simple\ Net\ Value\ of\ the\ project\ would\ be\ £100,000}}
\shortintertext{\hbox{Whilst for $2 \times 2$ we have:}}
&=£200,000-£100,000\\
&=£100,000
\end{align*}
$$


$$ \def\vmatrix#1{\left|\matrix{#1}\right|}
  \eqalignno{
    \vmatrix{a&b&c\cr d&e&f\cr g&h&i} &= aei + bfg + cdh - afh - bdi - ceg \cr
\noalign{\hbox{Whilst for $2 \times 2$ we have:}} % break away from the align
    \vmatrix{a&b\cr c&d} &= ad - bc
  }
$$

\noalign{\mathrm{Net\ Value}&=\mathrm{Total\ Net\ Revenues -\ Capital\ Outlay}\\}

Simple measures have the merit that they are easy to grasp as an idea and easy to calculate, but in neglecting discounting, they are likely to underestimate the actual pay back time and overestimate the actual net value of a project.. 

### The meaning of pay back time

To see this, we need to grasp what we mean by "pay back time". Let us here take this to mean, the time it takes for the project owners to be better off than if they had not carried out the project, but instead had used the money for some other purpose. 

Now, suppose instead the money had been put into an account with an interest rate of 5%. After 10 years, an initial sum of £100,000 would have increased in value by a factor $(1+0.05)^10 = 1.63$ and become worth £163,000. Hence our wind turbine project would not have left us in a better place, financially after ten years than the much easier alternative of putting the money in the bank account. We would by then have made good the original £100,000 outlay, but would be £63,000 worse off than if we had put the money in the bank account, or invested it in any other project that has earned us 5% of the outlay per year. In this sense, the project has not paid back after ten years, but will take longer to do so.

### The idea of discounting

In its simplest form, the discounting idea turns this view on its head and, instead of asking what a sum of money _R_ invested today would be worth in _i_ years time, if it accrued interest at _x_%, asks instead what sum of money $R_i$ would one need to invest now for it to be worth _R_ in _i_ years time, if the same interest rate of _x_% applied.This, in a sense, is what that sum of money, generated in the future, is _really_ worth to us today. We call this its _Present value_

In the context of an energy generation project that generated net cashflows $R_i$ in each year i of the project, we want to know what the present value of each of these future cash flows would be. When the sum of these flowa exceeds the initial capital outlay, the project can be said to have payed for itself. The time it takes for this to occur is the pay back time of the project, and the sum of all these discounted cash flows, minus the capital outlay, is the _Net Present value_ of the project. 

Elt's explore these ideas in the context of our wind turbine example.

If the wind turbine generates $R_5=£10,000$ of revenue in its fifth year of operation, what is that actuall worth to us today? Less than £10,000, to be sure, and $R_6$, the revenue generated in the 6th year would be weorth even less, and so on.

The _Net Present Value_ is a measure of the overall financial worth of the project, so it is the sum of all the annual cash flows over the lifetime of the project. Without discounting, this is simply the sum of the net annual revenues minus the initial capital cost. So, for our turbine example, this would be $20 \times £10000 - £100,000 = £100,000$
. 

extending this idea, 

This is calculated as follows

Assume a discount rate of 6% %. This means that for a sum of money to be worth £100 in 1 year's time, the sum that needs to be invested is £94.30, since $94.3 \times (1+0.06) =100$. If we need £100 in two years time, then the sum we need to invest is £89.00, since $89 \times (1+0.06)^2$ = 100. And so on. If we want a sum to worth £100 after n years, at 6% interest, we need to invest $100 / (1.06)n$.

Now, think of each of the annual earnings of the wind energy generation project mentioned above, over the 20 year life-time of the project. If those earnings are £10,000 per year, that sounds as though the project will earn a total of $20 \times £10,000 = £200,000$, so that with the initial outlay of £100,000, the net value (profit) of the project would be £100,000. But this is wrong because these earnings all occur at  times in the future, not now, so that their value on paper could be generated at those times by investing a smaller sum in the present : the further into the future they occur, the smaller that sum is.. The effective worth (usually referred to as the "present value") of the earnings of the n th year is $£10,000 / (1 + y/100)^n$, since that is the sum that needs to be invested, at y% interest rate, to generate £10,000 at a time n years in the future. This is the idea of discounting. The total present value of the annual earnings over the twenty years of the project is then the sum of these discounted annual earnings, and the so called net present value (NPV) of the project is this sum of discounted earnings less any costs of the project, which also must be discounted if they occur over an extended period of time. For most energy generation projects, there will be a large initial capital outlay and then a series of annual operation and maintenance costs, plus any borrowing repayments that need to be made.

The NPV of a project of lifetime N years, annual earnings x and discount rate y % is given by

$$\mathrm{NPV}=\displaystyle\sum_{n=1}^N\dfrac{x}{{\left(1+\frac{y}{100}\right)^n}}=x\displaystyle\sum_{n=1}^N\left(1+ \dfrac{y}{100}\right)^n$$	


This value will be less than the anuual earnings multiplied by the lifetime of the project.

The net present value of a project must be positive for the project to make any financial sense at all, since it represents the effective bank balance of the project at the end of its life: the earnings must exceed the costs, all values discounted to their present value. The greater the NPOV od a project, the more attractive it is.

The pay back time of the project will be the time it takes for the bank balance of the project to become positive. This time must be less than the lifetime of the project, and is often required to be very much less than that. Clearly, if the payback time of a project exceeds its lifetime, its NPV is negative, and the shorter the payback time the larger the NPV of a project is likely to be.

The internal rate of return (IRR) is the discount rate required to bring the NPV to zero. It is a measure of the value of a project and is a useful tool in comparing one project with another. The higher the IRR of a project, the greater the perceived likelihood that it will make a profit. Thuis if two investment schemes are available for the the same capital, the one that offers the higher IRR is the more attractive.